---
title: "CodeBook"
author: "Oscar Nieto"
date: "10/24/2020"
output: html_document
---
# DATA DICTIONARY - Human Activity Recognition Using Smartphones Data Set

## activity
type of activity performed by the the volunteers

  * WALKING
  * WALKING_UPSTAIRS
  * WALKING_DOWNSTAIRS
  * SITTING 
  * STANDING
  * LAYING

## subject
the reference for each of the volunteers

  * 1
  * 2
  * 3
  * 4
  * 5
  * 6
  * 7
  * 8
  * 9
  * 10
  * 11
  * 12
  * 13
  * 13
  * 14
  * 15
  * 16
  * 17
  * 18
  * 19
  * 20
  * 21
  * 22
  * 23
  * 24
  * 25
  * 26
  * 27
  * 28
  * 29
  * 30

## tBodyAcc-mean()-X
mean normalized time body acceleration on the X axis

 * [0.2216, 0.3015]
 
## tBodyAcc-mean()-Y
mean normalized time body acceleration on the X axis

 * [-0.040514, -0.001308]
 
## tBodyAcc-mean()-Z
mean normalized time body acceleration on the X axis

 * [-0.15251, -0.07538]
 
## tBodyAcc-std()-X
standart deviation of the normalized time body acceleration on the X axis

 * [-0.9961, 0.6269]
 
## tBodyAcc-std()-Y
standart deviation of the normalized time body acceleration on the Y axis

* [-0.99024, 0.61694]

## tBodyAcc-std()-Z
standart deviation of the normalized time body acceleration on the Z axis

* [-0.9877, 0.6090]

## tGravityAcc-mean()-X
mean normalized time gravity acceleration on the X axis

* [-0.6800, 0.9745]

## tGravityAcc-mean()-Y
mean normalized time gravity acceleration on the X axis

* [-0.47989, 0.95659]

## tGravityAcc-mean()-Z
mean normalized time gravity acceleration on the X axis

* [-0.49509, 0.95787]

## tGravityAcc-std()-X
standard deviation of the normalized time gravity acceleration on the X axis

* [-0.9968, -0.8296]

## tGravityAcc-std()-Y
standard deviation of the normalized time gravity acceleration on the Y axis

* [-0.9942, -0.6436]

## tGravityAcc-std()-Z
standard deviation of the normalized time gravity acceleration on the Z axis

* [-0.9910, -0.6102]

## tBodyAccJerk-mean()-X
mean time of the normalized jerk of the body acceleration on the X axis

* [-0.9910, -0.6102]

## tBodyAccJerk-mean()-Y
mean time of the normalized jerk of the body acceleration on the Y axis

* [-0.0386872, 0.0568186]

## tBodyAccJerk-mean()-Z
mean time of the normalized jerk of the body acceleration on the Z axis

* [-0.067458, 0.038053]

## tBodyAccJerk-std()-X
standard deviation of the normalized jerk of the body acceleration on the X axis

* [-0.9946, 0.5443]

## tBodyAccJerk-std()-Y
standard deviation of the normalized jerk of the body acceleration on the Y axis

* [-0.9895, 0.3553]

## tBodyAccJerk-std()-Z
standard deviation of the normalized jerk of the body acceleration on the Z axis

* [-0.99329, 0.03102]

## tBodyGyro-mean()-X
mean time of the normalized body angular velocity on the X axis

* [-0.20578, 0.19270]

## tBodyGyro-mean()-Y
mean time of the normalized body angular velocity on the Y axis

* [-0.20421, 0.02747]

## tBodyGyro-mean()-Z
mean time of the normalized body angular velocity on the Z axis

* [-0.07245, 0.17910]

## tBodyGyro-std()-X
standard deviation of the normalized body angular velocity on the X axis

* [-0.9943 , 0.2677]

## tBodyGyro-std()-Y
standard deviation of the normalized body angular velocity on the Y axis

* [-0.9942 , 0.4765]

## tBodyGyro-std()-Z
standard deviation of the normalized body angular velocity on the Z axis

* [-0.9855 , 0.5649]

## tBodyGyroJerk-mean()-X
mean time of the normalized jerk of the body angular velocity on the X axis

* [-0.15721, -0.02209]

## tBodyGyroJerk-mean()-Y
mean time of the normalized jerk of the body angular velocity on the Y axis

* [-0.07681, -0.01320]

## tBodyGyroJerk-mean()-Z
mean time of the normalized jerk of the body angular velocity on the Z axis

* [-0.092500, -0.006941]

## tBodyGyroJerk-std()-X
standard deviation of the normalized jerk of the body angular velocity on the X axis

* [-0.9965, 0.1791]

## tBodyGyroJerk-std()-Y
standard deviation of the normalized jerk of the body angular velocity on the Y axis

* [-0.9971, 0.2959]

## tBodyGyroJerk-std()-Z
standard deviation of the normalized jerk of the body angular velocity on the Z axis

* [-0.9954, 0.1932]

## tBodyAccMag-mean()
mean normalized time of the body acceleration magnitude

* [-0.9865, 0.6446]

## tBodyAccMag-std()
standard deviation of the normalized time of the body acceleration magnitude

* [-0.9865, 0.4284]

## tGravityAccMag-mean()
mean normalized time of the gravity acceleration magnitude

* [-0.9865, 0.6446]

## tGravityAccMag-std()
standard deviation of the normalized time gravity acceleration magnitude

* [-0.9865, 0.4284]

## tBodyAccJerkMag-mean()
mean normalized time jerk of the body acceleration magnitude

* [-0.9928, 0.4345 ]

## tBodyAccJerkMag-std()
standard deviation of the normalized time of the jerk body acceleration magnitude

* [-0.9946, 0.4506]

## tBodyGyroMag-mean()
mean normalized time of the body angular velocity magnitude

* [-0.9807, 0.4180]

## tBodyGyroMag-std()
standard deviation of the time of the body angular velocity magnitude

* [-0.9814, 0.3000]

## tBodyGyroJerkMag-mean()
mean normalized time of the jerk of the body angular velocity magnitude

* [-0.9814, 0.3000]

## tBodyGyroJerkMag-std()
standard deviation of the time jerk of the of the body angular velocity magnitude

* [-0.9977, 0.2502]


## fBodyAcc-mean()-X
mean normalized frequency body acceleration on the X axis

 * [0.2216, 0.3015]
 
## fBodyAcc-mean()-Y
mean normalized frequency body acceleration on the X axis

 * [-0.040514, -0.001308]
 
## fBodyAcc-mean()-Z
mean normalized frequency body acceleration on the X axis

 * [-0.15251, -0.07538]
 
## fBodyAcc-std()-X
standart deviation of the normalized frequency body acceleration on the X axis

 * [-0.9961, 0.6269]
 
## fBodyAcc-std()-Y
standart deviation of the normalized frequency body acceleration on the Y axis

* [-0.99024, 0.61694]

## fBodyAcc-std()-Z
standart deviation of the normalized frequency body acceleration on the Z axis

* [-0.9877, 0.6090]


